CREATE TABLE [dbo].[Orders] (
    [OWNRSHP_ID] FLOAT (53)    NULL,
    [SOURCE_ID]  VARCHAR (500) NULL,
    [ORDER_STS]  VARCHAR (500) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);

