CREATE TABLE [dbo].[TC2C_U01V10_GOESLSDP_TEMP_ACTUAL_CASH_FLOW_FEB_20201218_test1] (
    [COUNTRY_CD]              VARCHAR (2)     NULL,
    [CYCLE_DT]                INT             NULL,
    [POLICY_NUM]              VARCHAR (10)    NULL,
    [COV_PLAN_CD]             VARCHAR (20)    NULL,
    [BASIC_IND]               VARCHAR (1)     NULL,
    [COV_NUM]                 VARCHAR (6)     NULL,
    [CUK]                     VARCHAR (200)   NULL,
    [CASHFLOW_DT]             DATE            NULL,
    [ALLOCATION_IND]          VARCHAR (1)     NULL,
    [SOURCE_SYSTEM_CD]        VARCHAR (10)    NULL,
    [SOURCE_IDENTIFIER]       VARCHAR (10)    NULL,
    [SAP_COMPANY_CD]          VARCHAR (4)     NULL,
    [SAP_CURRENCY_CD]         VARCHAR (3)     NULL,
    [SAP_OCOA_CD]             VARCHAR (10)    NULL,
    [ENTITY_CD]               VARCHAR (4)     NULL,
    [ACF_LV1_CD]              VARCHAR (6)     NULL,
    [ACF_LV2_CD]              VARCHAR (6)     NULL,
    [I17_IND]                 VARCHAR (1)     NULL,
    [DIRECT_IND]              VARCHAR (1)     NULL,
    [PAYMENT_MODE]            INT             NULL,
    [YRT_CURR_SERVICE_PCT]    DECIMAL (28, 6) NULL,
    [CSM_GROUP]               VARCHAR (100)   NULL,
    [CSM_SUB_GROUP]           VARCHAR (100)   NULL,
    [AMT_SIGNAGE]             DECIMAL (28, 6) NULL,
    [ACF_UN_KEY]              VARCHAR (100)   NULL,
    [TXN_DT]                  DATE            NULL,
    [TXN_EFF_DT]              DATE            NULL,
    [SAP_SEGMENT]             VARCHAR (10)    NULL,
    [SAP_LOB]                 VARCHAR (10)    NULL,
    [SAP_CHANNEL_CD]          VARCHAR (10)    NULL,
    [SAP_OCI]                 VARCHAR (10)    NULL,
    [SAP_IFRS_CLASSIFICATION] VARCHAR (4)     NULL,
    [IFRS_CLASSIFICATION]     VARCHAR (4)     NULL,
    [SAP_LOCAL_LOB]           VARCHAR (30)    NULL,
    [SAP_TRADING_PARTNER]     VARCHAR (30)    NULL,
    [SAP_FUND_CD]             VARCHAR (30)    NULL,
    [SAP_LOCAL_BRANCH]        VARCHAR (30)    NULL,
    [SAP_LIABILITY_PORTFOLIO] VARCHAR (10)    NULL,
    [SAP_FLOW_TYPE]           VARCHAR (10)    NULL,
    [SAP_TRANSITION_APPROACH] VARCHAR (10)    NULL,
    [SAP_CODE_BLOCK_14]       VARCHAR (30)    NULL,
    [SAP_CODE_BLOCK_15]       VARCHAR (30)    NULL,
    [SAS_IND]                 VARCHAR (1)     NULL,
    [VARIED_UI_IND]           VARCHAR (1)     NULL,
    [FCF_PCA_IND]             VARCHAR (3)     NULL,
    [CONTRACT_BOUNDARY]       DECIMAL (28, 6) NULL,
    [PROFITABILITY_GROUP]     VARCHAR (3)     NULL,
    [HYBRID_IND]              VARCHAR (1)     NULL,
    [CURRENCY_TYPE]           VARCHAR (3)     NULL,
    [RI_SUB_GROUP]            VARCHAR (100)   NULL,
    [FINANCE_TREATY_CD]       VARCHAR (20)    NULL,
    [COOL_OFF_IND]            VARCHAR (1)     NULL,
    [MUTUALIZATION_CD]        VARCHAR (10)    NULL,
    [SWITCH_SIGNAGE]          INT             NULL,
    [IS_NEW_GEN_IND]          VARCHAR (1)     NULL,
    [RECORD_KEY]              VARCHAR (200)   NULL,
    [CREATED_TS]              DATETIME        NULL,
    [CREATED_BY]              VARCHAR (30)    NULL,
    [LAST_MODIFIED_TS]        DATETIME        NULL,
    [LAST_MODIFIED_BY]        VARCHAR (30)    NULL,
    [CSM_GROUP_NEW]           VARCHAR (100)   NULL,
    [CSM_SUB_GROUP_NEW]       VARCHAR (100)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

